name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install coverage
        pytest coverage run -m pytest tests/
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v3.1.1
