name: my first-workflow
on: [push]
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- run: pip install isort
      #- run: isort .
      - uses: isort/isort-action@v0.1.0
